baseURL = 'https://vivianwilde.github.io/watchtower-blog/'
languageCode = 'en-us'
title = "Morgana's Case Notes"
theme = 'm10c'
author = 'Morgan/a Ilkay'
[params]
author = 'Morgan/a Ilkay'
description = "Delving into the Mysteries of the WatchTower"


avatar = 'avatar.jpg'
[[menu.main]]
name = "Case Notes"
url = "/case-notes"
weight = 1
[[menu.main]]
name="Fanfic"
url="/fanfic"
weight=2
[[menu.main]]
name = "About"
title = "About"
url = "/about"
weight = 3

[pagination]
  # disableAliases = false
  pagerSize = 50
  path = 'page'
