* Morgana/Morgan Ilkay

#+begin_quote
A Watcher investigator with an eye for the truth and a sharpshooter's aim.
#+end_quote
** Hobbies
- Pensively staring out into the middle distance while blowing bubbles instead of smoking a cigarette.
- Going to speakeasies to pick up on rumours and news, asking for "a rum and coke, hold the rum. And make it a strong one", and watching the bartender try to figure out if it's some kind of trick.
- Time Candy Crush, but only the complex-numbered levels. Anything else isn't worth her time.
- Playing four-dimensional Sudoku during boring meetings.
- Being snarky about ChronoCo.

** Accomplishments
- Officially deemed a bigger threat than a small squadron of Knights, by none other than Malachai von Spatz himself.
- Took out an anti-aircraft gun by shooting into it just as it fired, detonating the rocket in it /while it was in the gun/.

** Accomplishments (Private)
- Got Enigma to get ice-cream with a ChronoCo employee.
- Got Enigma to make a joke.
- Got Enigma to laugh.
- Got Enigma to spend the night playing at a bouncy castle, willingly.
#+begin_quote
"Are there clues at the bouncy castle?"
"I don't know. I've never been to a Murder Mystery Bouncy Castle but now I desperately want to."
"Well if there are clues it is our duty to the Watchtower to investigate."
#+end_quote
