#+title: Enigma Memories
- Morgana and Enigma talking to Zephyr together and coordinating with little looks and whispers, agreeing almost instinctively on what pressure to put and what secrets we can safely share… and then swapping identical looks of frustration as Simon throws all that to the winds and starts telling the story.
- Creeping through a Hemlock base, Morgana sees Enigma get downed while rushing to the computer. A burst of protectiveness comes over them, and they send a bolt of lightning arcing towards whoever shot her. As the mooks disintegrate she holsters her gun and murmurs "you don't fuck with the Watchers" as she rushes over to stabilise Enigma. There's bravado there (Morgana was always a bit of a show-off) and a bit of Watcher patriotism, but mostly there's just the undercurrent of "stay away from my new friend".
- Taking little pictures of Enigma obssessing over every corner of the bouncy castle looking for clues, then finally convincing you to join them in jumping about like little kids until both of them are collapsed - Morgana giggling, and Enigma trying to hide her smile. Then Enigma finally falling asleep (on the bouncy castle), and Morgana nervously throwing their watcher uniform jacket over her like a blanket (trying not to touch her in case Enigma's skin ignites at physical contact).
- A meeting over coffee (Enigma's drinking it black with no sugar, Morgana's got something with chocolate and caramel and is already halfway through theirs), swapping hypotheses and complimenting each others' case notes. Morgana's thoughts are a mess of leads and questions, but those quickly fade away compared to her sheer joy of meeting someone else who /understands/, another Watcher who'll think things through and make connections the way she does.
- Morgana opening the door to Miri's mansion and seeing Enigma decided to join them; Excitedly pulling Enigma in to meet the rest of the crew (ignoring her protests) and going "hi everyone! This is my +friend+ trusted colleague Enigma, she's the coolest. Anyway, she's a Watcher, I invited her to come explore with us".
- Morgana introducing Enigma to Miri and saying "I'm sure you'll both get along great!" in a strained voice that can only be described as 'kindergarden teacher lying through their teeth'.
- Anxiously watching the bomb defusal process and praying to every god they could remember the name of. Watching Izzy's gadget pry the bomb out and instinctively running over to hug Enigma, then seeing the bomb in her hand and hurriedly tossing it away. When paradox introduces itself Morgana's barely listening. They're too busy revelling in the fact that Enigma's alive.
- Morgana's surrounded by Hemlock goons and staring daggers at Damien, trying to calculate their best ways of getting out - surrender and trust Malachai, or try to sneak away and hope no one is perceptive enough to notice? Then they hear the telltale /blip/ of Enigma's teleport and instinctively relax a little - whatever happens, they're pretty sure the two of them can pull through it no problem. In the ensuing whatever-the-hell-Damien-is-doing they manage to sneak back to Enigma's side, and even amid the blood and chaos it feels a little like coming home. Later, when Enigma pulls them in to teleport out, Morgana abent-mindedly puts their arm around Enigma as well, and keeps holding on to her once they're out.
- Discussing secret anti-paradox plans in Izzy's apartment. Protectively moving closer to Enigma when Izzy mentions that someone might have to die. Then, seeing you freak out over Galloway and staring daggers at Izzy trying to shut her up. And finally seeing you calm down a little and pet Izzy's cats, and filing away "Enigma likes cats" in their mind.
- The bloodhounds are in front of a whiteboard, diagramming a messy set of loops. Morgana says "Hey Enigma, maybe you're future Miri! It'd explain where your angsty YA-protagonist prickliness comes from". They begin to draw an arrow in blue before Enigma tackles the marker out of her hand and they both fall over. Morgana pulls herself up, but she's laughing so hard she collapses back down a second later.
- Morgana is sitting across from Enigma sipping a cherry soda out of a champagne flute, when they impulsively raise their glass and toast "to friendship", mostly to get a rise out of her. They're ready to put it down (they even have a teasing remark ready for when they do), but as they pull it back Enigma rolls her eyes and grudgingly raises her own glass. Morgana hides their excitement (insofar as she ever hid anything from Enigma) but the little one-sided "to friendship" toast becomes a little ritual of hers.
- Enigma sulking in a headlock because no one will let her martyr herself like an idiot, and Morgana trying to keep her from teleporting out without accidentally hurting her. As Enigma struggles, Morgana ponders 'what would shut /me/ up if that was me?'. With an impish grin, she whispers "if you stop trying to escape, I have some secrets for you". It's a transparent lie - every insight they have has already been sent to Enigma, usually at one in the morning with a heart emoji (or several) inexplicably attached (they get sentimental when they're tired, okay?). They're almost a tiny little bit hurt when Enigma stops struggling, but they take their chance to re-adjust the headlock and then whisper "the secret is that I trust you, dummy. Don't worry".
- Morgana idly scrolling Timeblr and reflexively clicking 'share' on a cat photo, before awkwardly backing out of it. She then hesitates for a long moment before saving it to a folder named 'Enigma' (you recognise the folder - it got dead-man's-switched to Enigma when she died). Most of them look just like Izzy's cats.
- A supercut of disconnected voices, none of them Enigma's. Miri whispering "I know she's your /best friend/ but I don't want to let her in", Rosemary casually going "maybe your /friend/ Enigma knows more about the Watchers side of it", and finally a bitter, acrid one of Larry going "well, you like Enigma, Enigma likes you, tell us what you know and you can both walk out alive".
- Another supercut, this time of several memories of being punched by Enigma, and reactions slowly evolving from outrage to 'wanting to give her a hug'.
