#+title: Juniper

An actual non-jokey epilogue for Juniper Snow.
* Wizardry
- Lone Master's spellbook: Picks up a few secrets from it, keeps it on their shelf as a memento. They're hoping to learn enough to understand it one day.
- She does some freelance work for Lightborn, like being a guinea pig, doing security/infiltration assignments, or occassionally leading strike teams, in return for cutting-edge hologram tech
* Work
- Abandons the Watchers - she bears them no ill will, she just needs a change of scene
- Still in touch with Eyes (and Enigma by proxy, although they never grow really close)
- She joins the minutemen, and serves as Breacher's unofficial left hand man/woman/[REDACTED] and informal head of their intelligence apparatus
- Mainly doing the kind of investigation/espionage that a councillor can't officially endorse
- She tries to develop Eyes' spooky habit of knowing secrets, but never really perfects it.
- When things come close to physical blows, she's usually the one in charge of setting up a forcefield between the two parties and telling them to sit in the corner and think about what they've done
