#+title: Watchtower Queer Headcanons
#+options: toc:nil
#+LATEX_HEADER: \usepackage[margin=0.4in]{geometry}

I know a lot of characters were explicitly queer, this is mostly ones that /weren't/ explicitly canon. I've only put the characters I had headcanons for; let me know if you think there are any glaring omissions.

Also yes this is LaTeX, don't judge me.

* Watchers
- Enigma :: Nonbinary lesbian. The inherent transness of choosing your own name and rejecting the one your abusive father-figure gave you.
- Morgana :: Transfem Genderfluid. Got her egg cracked by seeing Jane basically shapeshift via disguises, and uses a receptacle purely because it's gender.
- Sidney Stockton :: Arospec, acespec. Just based on vibes.
- Marlow MacPhearson :: Gay, but transphobic.
- Nicholas Aurora/Eyes Unseen :: Bicurious.
- Jane Doe :: Genderfluid. Jane Doe's masks should be covered as gender-affirming care by insurance.
- Larry Morton :: Homophobic
- Tuhorn :: Gay. He's Gandalf-coded and Ian Mckellen is gay
- Lone Master :: Aroace. His estate is mostly just a giant bakery for making obscene amounts of garlic bread.
- Barney :: Gay. He's into vintage fashion.
- Whisperer :: Trans but in denial. The creepy cloak is just a dysphoria hoodie.
* Minutemen
- The Rat :: Furry. Obviously.
- Breacher :: Trans, Ace. Trans because of all the name changes, ace just based on vibes.
- Magpie :: Moneysexual
- Phantom of the Disco :: Pan.
- Grasshopper :: Trans. All cyborgs are trans.
* Knights
- Creel :: Trans woman. The reason she wears the helmet all the time is because of gender dysphoria.
- Tracker :: Furry, aroace. He just gives "aroace bestie" vibes.
- Tilda Clinton :: [REDACTED]
* ChronoCo
- AC-001x :: Nonbinary. Because robot.
- Rachel Anderson :: Trans. Because robots.
- Holly Holland :: Homophobic. Yes I know she's gay.
- John TIME :: Multigender. So as to be maximally relatable to consumers of all genders.
- Hurlabur :: Nonbinary aspec. He's the real reason frogs are a nonbinary meme. In a QPR with John Hannaly.
- Simon Bastil :: See /Grasshopper/
* Hemlock
- Malakai Von Spatz :: Trans nonbinary. You can't have a name like Malakai Von Spatz and be cis.
- Paradox :: Bigender. Because they're a pair o' docs.
- Izzy Spatz :: Transgender (I don't care how). Dying and being reborn and changing your name mid-campaign is transgender.
- Damien :: Pansexual transmasc drag king. I do not need to elaborate.
- Robo-Stalin :: Communist. Yes that counts because I say so.
* Secondhand
- Quaid :: French.
- Piglet :: Lesbian, because portals are lesbian (citation: https://en.wikipedia.org/wiki/Portal_(series))
- Riley :: Genderfluid. Having a receptacle makes you genderfluid, I don't make the rules.
