#+title: The Last Will and Testament of Morgana Ilkay

I Morgan/a Ilkay of the Watchtower, being of sound mind[fn:1] and body, declare this to be my Last Will and Testament, and revoke all previous wills and codicils made by me, either jointly or severally.

** To Magpie
My organs.

My collection of modern guns. Put a hole in the right people with them.

** To Enigma
All the bubble blowers.
My Watcher uniform. Wear something with colors for once, it won't kill you.
Collection of autographed classic mystery novels. Feel free to turn them in to Watcher HQ if the signatures represent anomalies.

** To Rosemary
A Girl in Red CD
Autographed pictures from when we snuck out to a concert in the 21st century



** To Breacher
All my case notes.
My supply of red string for the conspiracy board. I realise you won't find it very useful but dammit there is such a thing as tradition.

** To Izzy
I leave my computer, and all my technical equipment. Maybe you can actually make it work, god knows I never could.

** To Simon
Try some soda.

** To Jane Doe

** To Larry Morton
There's a cup of yogurt from four years ago in my fridge. Fucking choke on it.

** To Miri
The complete discography of the /best/ boy band ever. (The Jeremies)

** To Stockton

** To the Secondhand

* Footnotes

[fn:1] Insofar as anyone can be of sound mind while still being friends with Simon Bastil
