---
title: Ancient Greece
tags: ['Ace Squad']
date: 2024-06-02
---
* <2024-06-02 Sun>First Session Let's Fucking Go!
** Receptacle
Adel Boiss - Persian Spy
W: +3   A: +4    T: +2    C:+2    H:+0
Ability - Persian Connections: The Persians, an opposing military force, trust Boiss's decrees...
** Case
Temporal anomaly - symptoms of sickness, etc.
** NPC: Selene
Assistant to Madame E, Watcher
We've worked together, casually.
** Notes
- A thief escaped and disappeared into the timestream, stole a list of some sensitive info
** Time
- Exits: One, presumably a thief
- Exit to ancient greece around 500BC, caused a ripple leading to a break in 480.


- Knights are going to attack the secondhand revolution.
- Some are out investigating?
** Athens
Persian invasion never got this far

It helped with the fleet. s
We had spies in politics.
We had help with the fleet.
Phoenicians helped Persians nuke the fleet.
This is fine.
Battle of Salamas - big battle, Phoenicians + Persians + Ionians vs misc Greeks.
They should have failed, in this timeline they succeeded

500: In Salamas, Th was attacked + captured by pirates, needed to be bailed out by council ransom, lost face.
Ar rose in prestige after that.
Scribe investigated, did the payments, we have a name to seek out.
** 500
Strange figures arrived recently:
Nobleman with a strange pulsing scar
Athenian, doing an inspection of merchant goods

The nobleman is the more interesting one.

Someone at the docks is basically trafficking/smuggling. Perhaps he's had some business recently.
Odd requests: Scar man wanted something in a box carried to a contact.

Questions: Who was the contact.


Bald man introduced scarman to Man in black, heavily armed

Man in black - Pointy sticks across the chest.
Advanced modern weaponry?
*** Cold case!
5 hours before we landed, the bald merchant introduced scarman to the man in black

Morgan commits scarman details to memory

Pirate has a bandolier and a bow

Pirate's name: Adamantius

Bald guy: Baldius

Box seems about 10th century, way out of time.
Heavy, probably concerning.

Rosemary got a 20! In a d12 system! WTF!
