---
draft: true
title: Dalton Family Ball
date: 2024-07-17
---
* Planning
** If we kill Larry
- Blame ChronoCo and go to war
- Blame the Secondhand, bipartisan nuke us for councillor-killing and then cheer squad does cheer squad things
- How do we
** State of play
- Marlow wants to kill Larry
- Enigma also seems to
- Phoenix, Izzy and I are hoping to incriminate him rather than kill, and protect whoever Larry is targeting.
* Costume
** Full AC
- Eh, not really
** AC/Juniper
- Mask: Golden/yellow light around the eyeholes, polished metal all around and bronze gear and circuit designs (including a large gear on the side as the "accessory") (camera and sensor/scanner capabilities)
- A facemask that looks like a grille/speaker (audio recording, optionally communicating with the group)
- Metallic-grey robes with accents in ChronoCo gold and knightly red trimmings
- A little commemorative Velociraptor pin from Dinosaur Park
- Ace pride pins because puns
- A little handcuff keychain hanging from a belt loop
* The Game
- Dalton has anti-hologram tech
- Tell Sam: I forgot to say this because I was talking with Miri, but Juniper would've gotten there a little early to search for camera and security system blind spots
** Larry
- Threads have blue traces pointing to where they are
- 
** Jane Doe's entry
- She has someone new by her side
- Dr. Fell, mad scientist, destabiliser designer.
- She wanted to know where Dalton was.
- Resists physical+mental, vulnerable to temporal, partial resist energy
- Jane walks towards the hedge maze
*** Jane and Jett
- Jett: Is it true you're trying to start the apocalypse?
- Jane: We're trying to save the timeline
- Jett: I need to go think about this
** Clinton
- Worried, without a +1, shaking hand and tapping foot
- Shaky, but not mind-numbed
** Jett
- Trusted associate of Alec Wilde (and then killed him)
** Nic and Eyes
- Our stuff was confiscated, including snowglobes
- So we're out of weapons
- Told (probably by Enigma) that Watchers suspect Nic
- Nic might "reveal" himself as a Watcher loyalist to stay safe and on the inside, but he's one of ours.
- Nic needs a private audience with Dalton
- We have a potential distraction - Phantom starting a dance party.
* Books
Takes one, rearranges 3

NULBI NAI THY ZOU NAI WQOWR. XIIN KV NAI WALFIQ OZ WAUOVO WO.


NAI is very common



LOTR was in some order before, then she corrected the order
LOTR: 1,2,3
She took Hobbit which is the prequel.
* Hedge maze
Jane and Larry are meeting
We lose her for a bit, she's deep in the maze
Threads: 10 are accounted for
Both Jane and Larry's threads are pointing to the party

I found Larry Morton

Jane is speed-boosted

Clinton is tailing Jane, no thread hints

Larry: Threads leading deeper into the maze

* Grasshopper
- No threads via kaleidoscope
- Larry's hand is shaking, just like Tasha
** Larry Talking
- "We should continue with this plan"
- "Be prepared to tie him up" -- So basically Larry plans to thread Dalton?
- "Don't release him now"
-
