---
date: 2024-07-12
title: Knight Falls On Dutch Shores
---
* Simon's Presentation
** Florence
- Simon reacted Gnomeo and Juliet in Florence
- 
* Objectives
- Kill Holly Holland
- Hold/Take the Stabilizer
- Transport Time Fluid through the Refinery
* Actual Game
- Holly's at war, threatened to blow up the moon
- Minuteman are screwed, Breacher and Wilde are dead
- Automatons decommissioned but the knights want the last few for the war against Holland
- We want to fight our way to Holly's timeline room
- Then find which Timeline she's in
- Then take control of the time stabilizer
- Chronite: Large amounts of it dilates time, but volatile and can do temporal damage if pressurised/etc.
- Volatile pressurised chronite: Create a jump to nowhere
** Moon Mines
- Not too many physical fortifications
- Just warm bodies
- Magpie and Saint Nick are sneaking down the elevator
- Refinery is now pulling in weapons from other timelines
- Timeline room is sealed off but people are coming out, new conscripts
- Simon blew up the refinery and created a black hole
** Labs
- Mostly junk, good stuff has left
- Metal lockers with some important stuff


** Alternate Timeline
- Larry Morton sends Watchers with pocket-watches to the left
- Planting timeline-destroyer machines
- We need to take out 2 to get them, ideally 3
- We got caught, spooked by Enigma
- We took out 2, if we can circle back and get to a third
- Enigma can't yet TP as a bonus/free action
- Holland is dead.
- We have plans for Holly's stabiliser as well as some parts
- We have cheer squad destabiliser tech

Great news everyone, I believe we got an objective done!
Bad news is that Holly Holland is dead due to reasons, so the spark has been lit and we have no allies on the council, but I'm confident we can still wrangle a success.

* Speculation: Selene
Also guys a thought I had - Selene has known about Holly's weird timelines for a while, and we know Selene was involved in helping Tasha get the parts for the stabiliser that we've found so far. We know 2/3 of the plans are missing or nonexistent.

I'm wondering - it's possible Selene's disappeared into one of Holly's time-dilated timelines and has been making progress on the stabiliser that can give us a boost. There's no concrete evidence for this, but it's consistent with what we know, and it means that if we can find Selene before the Watchers do, and get her to safety, it might help us cross the finish line.

Other than that, she definitely still knows more about Holland's timeline engines than we do, she should be able to give us something
