---
draft: true
---

* Secrets: Wednesday Traitor
- Stolen intel: 36 hours unaccounted for, enough time for the code to have been decrypted. Could be Hemlock.
- Stolen again somewhere between Florence and Italy.
- The missing 36 hours is between the Egypt recovery and the return to Tower custody. Conjecture: Spy in the Wednesday group.


- Malachai showed up on Tasha's conspiracy boards and also the film
- More on the Kaleidoscope that was in Tasha's hands
- Look for entries/exits logged on the auxiliary time engine to follow Selene
- Talk to frog about lost receptacle shipment - maybe Tasha got her receptacle from there somehow.

* Speculation
It looks like advanced technology development is underway in secret, likely related to revivification.
And Hemlock and Secondhand are heavily involved. Hemlock seems to be the planner, tentatively. 
Jake Robertson was tester. Corroborates hints about Florence death being "all according to plan" from Greece man. 
Holly's secretly mining for some material important to the effort. 

* Leads
** Concrete
- Watchtower agents: We have contact info of book club agents. If we can do some work to put names to those, that could get us something to chase down.
- Last Resort, Under the Lake
- Selene's house
- Pompeii, flush out Mildred
- Thorwald: Useful idiot, also knight was involved in the murder.
- Vault door in Tasha's estate
- Trace the clay doll
** Hard to Use/Played Out
- Rosemary: She doesn't know why she's on the board, we can talk with her.
- Clinton
- Mr Time is suspicious
- "Freedom of the Watchtower", secondhand club
** Abstract
- Who got Tasha a receptacle? Frog probably involved (stolen from)
- Who all has Tasha receptacled into?
- Reagan??
- Holly's advanced tech
- Malachai in the film
- What was the Kaleidoscope thing
- Receptacle chamber in Tasha's house, whose? Remember she had a receptacle manual, that was stored with the letters from mysterious person. Inchresting
- NOTE From Breacher: Lost in transit means that a shipment of receptacles was stolen from the frog - perhaps given to Tasha, perhaps even to Scarman.
** Tuhorn
- Will: A sculpture of a frog for Councilor Tuhorn of the Forest
- Tuhorn opposes everything in council 
- Might have sent Jake Robertson
- Was late to emergency meeting
- Works with animals, and we have the chimpanzee dead drop
- Tuhorn’s loyalty is questioned by Thorwald. (The "useful idiot")

** Spies <2024-06-22 Sat>
- "Congrats on council campaign, after this I'm sure you'll be a big success."
- Could reference last week of sessions (i.e last Fri/Sun/Wed). Who came out of those looking good? Mr. Time, really. That's about it.
- "Recent assignment to the Watchers should prove most fruitful with our dastardly deeds."
- Clown is suspicious as hell: Either Hemlock has insight into her weird eldritch dinosaur shenanigans, or she's an agent

- Stockton: How long have they been with us?
- Rosemary? I sure hope not. But they do have schemes afoot.
- Rain: Plausible
- Magpie: Plausible
- Councillor: Mr Time and Clown are sus. This looks like a chronoco plot.
- Breacher: "Recently joining the watchers"


* Putting Pieces Together
# - LRS shows up a lot
- Tasha "no receptacle, it can't be used". In light of recent receptacle-related plans and shenanigans, how much did she know about the secondhand/hemlock/robertson body-swap timehop bullshit.
# - Clinton's showing up a lot.
** Receptacle
- Receptacle tank and manual on Tasha's estate
- Question: Could you receptacle into someone, say 3 days ago outside the watchtower, and then that body enters the watchtower (via either time-travelling their body in, or just physically walking in)
- Say, by using the auxiliary time engine to beam in?
- Cold case insights: Knight officer, gold, soft hands


* What we know
- Holly is doing mysterious mining for not time fluid without council knowledge 
- Tasha was collaborating with the second hand revolution
- Selene was feeding her info somehow
- Second-hand engineered a theft and a distraction by the scarred men.
* Leads on finding Selene
- Selene's house
- Miri?
- Tilda - what did she tell Tasha?
- "Enemy of my enemy" might refer to Selene
- kaleidoscope object
- last resort/lrs

* Enigma Secret
- Nothing set. I don't know quite what I'm doing
- One of the spies: New Recruit.
- Brad: New recruit to the Watchers. We don't know anything else suspicious about him.
- Morgana wants to cold case him at some point, Enigma is ok with it but will not be helping/endorsing
