---
title: Tuhorn
draft: true
date: 2024-06-24
---

* Tuhorn Convo <2024-06-24 Mon>
- Tuhorn has a secret hobbit hole in providence park
- Who sent the invite: "Dearest friend and your friend too, [points at breacher] she was perhaps but one of two"
- What was he doing: "Scanning, looking far, trying to end the war"
- "Perhaps I need a lift", "Watcher might work, but sometimes they don't when they're ruled by a jerk". All of them are jerks
- Madame E: Jerk. "Two of them may come here now", "they make the rift". A metaphorical rift, keeping Tuhorn and Breacher apart.
- INSIGHT: If Madame E is a jerk, Selene is probably acting alone.
- But we have Tasha "not sure if she can trust Madame E"
- "The perks are that you see everything. And when I saw, I understood"
- "One missing piece or the cure to bring the peace"
- The piece: The animal.
- The Watchers caused the war because it's always what happened. Preserving the timeline.
- Holly serves as the spark. "Last camel on the ark". So basically her mining operations are the final straw/pretext for factional disintegration.
- Watchers are the only ones who know, and we're working towards the war. Fuck. Are we the baddies
- ChronoCo: Weapon makers. "We want war but not too much". So they don't want an apocalyptic time war, but they will escalate into one.
- Hemlock disappears in the end, "Malachai "
- Selene didn't find this from Tuhorn. She worked with a friend who met a fateful end.
- So, it seems like Tuhorn gave
- In Council Four. Two from secondhand plus me, two more
- Holly's place of rest is a clue. Go back to LRS, find the clown. The one who brought Hemlock down, but also brought it up to serve a purpose (which we don't know)
- Is Hemlock trying to stop the war: "Of sorts"
- I think Morgana you're mistook, remember Malachai's favorite comic book
- Larry and Jane Doe are here with watcher militia, trying to get at Tuhorn.
- "Another book club member, on the council"
- The last one you know as well, raised in the fires of hell.
- I believe he implied he's not the one who tipped off Selene.
** Book club/Agents
- Scientist: Probably Robertson
- Sel: Selene
- Met a fateful end: Tasha
- Someone Breacher knows well, from the fires of hell. Could be MacIntyre?
** Hemlock Plans
- Their purpose you may have mistook, recall Malachai's favorite comic book
- Comic book: Watchmen. Oh I don't like this.
  #+begin_quote
  Veidt explains that he plans to save humanity from an impending nuclear war by staging a fake alien invasion and killing half the population of New York, forcing the United States and the Soviet Union to unite against a common enemy
  #+end_quote

  #+begin_quote
  they are confronted by mass destruction and death in New York, with a gigantic squid-like creature, created by Veidt's laboratories, dead in the middle of the city.
  #+end_quote
